default_platform(:android)

platform :android do
  before_all do
    ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_KEY"] = ENV["PLAY_STORE_SERVICE_ACCOUNT_JSON_PLAINTEXT"]
    ENV["PACKAGE_NAME"] = "digital.tonima.kairos"
  end

  desc "Build and upload release AAB for the phone app to Google Play"
  lane :deploy_phone do |options|
    version_code = options[:version_code]
    version_name = options[:version_name]

    gradle(
      task: ":app:bundleRelease",
      properties: {
        "android.injected.version.code" => version_code,
        "android.injected.version.name" => version_name,
        "android.injected.signing.store.file" => File.absolute_path("app/release-key.jks"),
        "android.injected.signing.store.password" => ENV["ANDROID_SIGNING_KEY_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_SIGNING_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_SIGNING_KEY_ALIAS_PASSWORD"]
      }
    )

    aab_path = Dir["app/build/outputs/bundle/release/*.aab"].first
    UI.user_error! "Could not find release AAB for phone app in #{aab_path}" unless File.exist?(aab_path)

    supply(
      package_name: ENV["PACKAGE_NAME"],
      aab: aab_path,
      track: "internal",
      json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_KEY"],
      version_code: version_code,
      version_name: version_name,
      skip_metadata: true,
      skip_screenshots: true,
      skip_upload_changelogs: true,
    )
  end

  desc "Build and upload release AAB for the Wear OS app to Google Play"
  lane :deploy_wear do |options|
    version_code = options[:version_code]
    version_name = options[:version_name]

    gradle(
      task: ":wear:bundleRelease",
      properties: {
        "android.injected.version.code" => version_code,
        "android.injected.version.name" => version_name,
        "android.injected.signing.store.file" => File.absolute_path("wear/release-key.jks"),
        "android.injected.signing.store.password" => ENV["ANDROID_SIGNING_KEY_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_SIGNING_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_SIGNING_KEY_ALIAS_PASSWORD"]
      }
    )

    aab_path = Dir["wear/build/outputs/bundle/release/*.aab"].first
    UI.user_error! "Could not find release AAB for wear app in #{aab_path}" unless File.exist?(aab_path)

    supply(
      package_name: ENV["PACKAGE_NAME"],
      aab: aab_path,
      track: "wear:internal",
      json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_KEY"],
      version_code: version_code,
      version_name: version_name,
      skip_metadata: true,
      skip_screenshots: true,
      skip_upload_changelogs: true
    )
  end
end
