name: Android CI - Kairos Multi-Module

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Lint and Test
    if: "!contains(github.event.head_commit.message, 'ci: Bump version')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/google-services.json
      - run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > wear/google-services.json

      - run: chmod +x gradlew
      - run: ./gradlew spotlessCheck
      - run: ./gradlew :core:testDebugUnitTest
      - run: ./gradlew :app:testDebugUnitTest
      - run: ./gradlew :wear:testDebugUnitTest


  version_bumper:
    name: Bump Version
    if: "!contains(github.event.head_commit.message, 'ci: Bump version')"
    needs: build
    runs-on: ubuntu-latest
    outputs:
      version_code: ${{ steps.version_bumper_script.outputs.version_code }}
      version_name: ${{ steps.version_bumper_script.outputs.version_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - id: version_bumper_script
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          NEW_VERSION_CODE=$(($GITHUB_RUN_NUMBER * 2))

          sed -i "s/APP_VERSION_CODE=.*/APP_VERSION_CODE=$NEW_VERSION_CODE/" gradle.properties

          VERSION_NAME=$(grep "APP_VERSION_NAME" gradle.properties | cut -d'=' -f2)
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION_NAME"
          VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
          NEW_VERSION_NAME="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
          sed -i "s/APP_VERSION_NAME=.*/APP_VERSION_NAME=$NEW_VERSION_NAME/" gradle.properties
          echo "version_name=$NEW_VERSION_NAME" >> $GITHUB_OUTPUT
          echo "version_code=$NEW_VERSION_CODE" >> $GITHUB_OUTPUT

          git add gradle.properties
          if ! git diff --staged --quiet; then
            git commit -m "ci: Bump version to $NEW_VERSION_NAME ($NEW_VERSION_CODE)"
            git push
          else
            echo "No version changes to commit."
          fi

  deploy_phone:
    name: Build, Sign and Deploy Phone App
    needs: version_bumper
    runs-on: ubuntu-latest
    environment:
      name: play-store-release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - run: chmod +x gradlew

      - run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/google-services.json
      - run: echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > app/release-key.jks

      - env:
          PLAY_STORE_SERVICE_ACCOUNT_JSON_PLAINTEXT: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
          ANDROID_SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ANDROID_SIGNING_KEY_ALIAS_PASSWORD: ${{ secrets.SIGNING_KEY_ALIAS_PASSWORD }}
          REPO_ROOT: ${{ github.workspace }}
        run: |
          bundle exec fastlane deploy_phone \
            version_code:${{ needs.version_bumper.outputs.version_code }} \
            version_name:${{ needs.version_bumper.outputs.version_name }}

  deploy_wear:
    name: Build, Sign and Deploy Wear OS App
    needs: version_bumper
    runs-on: ubuntu-latest
    environment:
      name: play-store-release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - run: chmod +x gradlew
      - run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > wear/google-services.json
      - run: echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > wear/release-key.jks

      - env:
          PLAY_STORE_SERVICE_ACCOUNT_JSON_PLAINTEXT: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
          ANDROID_SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ANDROID_SIGNING_KEY_ALIAS_PASSWORD: ${{ secrets.SIGNING_KEY_ALIAS_PASSWORD }}
          REPO_ROOT: ${{ github.workspace }}
        run: |
          bundle exec fastlane deploy_wear \
            version_code:${{ needs.version_bumper.outputs.version_code }} \
            version_name:${{ needs.version_bumper.outputs.version_name }}

  create_release:
    name: Create GitHub Tag and Release
    needs: [deploy_phone, deploy_wear]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - run: |
          echo "VERSION_NAME=${{ needs.version_bumper.outputs.version_name }}" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_NAME }}
          name: Release v${{ env.VERSION_NAME }}
          body: "Automatic release of version ${{ env.VERSION_NAME }} via GitHub Actions to Android and Wear OS."
